# Generated by Django 3.2.6 on 2021-12-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftSpace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=16)),
                ('trackingID', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('recipient', models.CharField(max_length=32)),
            ],
        ),
    ]
